Base Timer
AyullaLLC/JSTimer pull request #1
Opened 2018-04-21 15:17 UTC by ongwu2014

Implement Ayulla-JSTimer with no added features.

2018-04-24 05:33 UTC, HunterXHunterT9O requested changes

2018-04-24 05:33 UTC, HunterXHunterT9O commented on src/ayulla-jstimer.js
> +        if (settings.totalTime == 0) {
When is `totalTime` added to `settings`?
Is it part of `options`?

2018-04-24 10:34 UTC, ongwu2014 commented on src/ayulla-jstimer.js
> +        if (settings.totalTime == 0) {
No, it’s not part of options, it’s a required argument. You can see how it’s provided to the plugin from the sample html file.

The plugin (line 8) takes two arguments, time and options. The time argument is then assigned to totalTime (line 9).

2018-05-08 09:10 UTC, HunterXHunterT9O approved these changes

2018-05-08 12:09 UTC, merged